apiVersion: 1

datasources:
  - name: Flagent Postgres
    type: postgres
    access: proxy
    url: ${POSTGRES_HOST}:${POSTGRES_PORT}
    database: ${POSTGRES_DB}
    user: ${POSTGRES_USER}
    secureJsonData:
      password: ${POSTGRES_PASSWORD}
    jsonData:
      sslmode: 'disable'
      postgresVersion: 1400
      timescaledb: false
    editable: true
    isDefault: true
