name: flagent_enhanced
description: Enhanced Flutter/Dart client for Flagent API with caching and convenient API
version: 0.1.5
homepage: https://github.com/MaxLuxs/Flagent
repository: https://github.com/MaxLuxs/Flagent
publish_to: none

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flagent_client:
    path: ../dart
  dio: '^5.7.0'
  built_collection: '>=5.1.1 <6.0.0'
  built_value: '>=8.4.0 <9.0.0'

dev_dependencies:
  test: ^1.24.0
